### ISSUE TITLE
cognito:username is not the name in Cognito

### ISSUE THREAD

**Issue by AndersonatAMC** [mblackgeo/flask-cognito-lib#13]
When my user registers with Cognito, he provides a user name like "John", but in session I can only see `cognito:username: "75b7c437-a779-4fe0-80d0-e827d2a4cb44"` and `"sub: "75b7c437-a779-4fe0-80d0-e827d2a4cb44"`

**Comment by mblackgeo** [comment]
Please consult the [AWS Cognito documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html) for this issue
