### ISSUE TITLE
How to redirect to original route after logging in

### ISSUE THREAD

**Issue by Ulthran** [mblackgeo/flask-cognito-lib#46]
If you navigate to a route marked with `@authrequired`, after successful login it will redirect according to whatever is in the `postlogin` route. How do you set this dynamically based on the original route?

**Comment by mblackgeo** [comment]
I think the best way would be to store the state value in the session, from the docs:

```
    # An optional "state" value can be set in the current session which will
    # be passed and then used in the postlogin route (after the user has logged
    # into the Cognito hosted UI); this could be used for dynamic redirects,
    # for example, set `session['state'] = "some_custom_value"` before passing
    # the user to this route

```
