### ISSUE TITLE
Bump vulnerable "cryptography" library version

### ISSUE THREAD

**Issue by yesseyev** [mblackgeo/flask-cognito-lib#48]
Hi everyone,
We've started using your awesome lib, but getting issues with vulnerability checks for `cryptography = "^41.0.5"`, as stated in [here](https://github.com/mblackgeo/flask-cognito-lib/blob/main/pyproject.toml#L34).
  
1) **NULL pointer deference with pkcs12.serialize_key_and_certificates when called with a non-matching certificate and private key and an hmac_hash override** ([link](https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4))
2) **Bleichenbacher timing oracle attack** ([link](https://vulners.com/github/GHSA-3WW4-GG4F-JR7F))

To resolve it **cryptography** version must be at least `cryptography = "^42.0.4"`.

If anyone could bump it in `pyproject.toml` and `poetry.lock` files.
Thanks

**Comment by mblackgeo** [comment]
Thanks, released in v1.8.2 :tada: 
https://github.com/mblackgeo/flask-cognito-lib/releases/tag/v1.8.2
