### ISSUE TITLE
Cryptography Package: GHSA-h4gh-qq45-vh27

### ISSUE THREAD

**Issue by Hargrav3s** [mblackgeo/flask-cognito-lib#51]
Hello! Love your package, I'm trying to get one of my docker images out of any vulnerabilities, and noticed this pop up, is there any timeline of when this package could be updated to use `43.0.1` or later?

Specifically this vulnerability: [GHSA-h4gh-qq45-vh27](https://github.com/advisories/GHSA-h4gh-qq45-vh27)

**Comment by mblackgeo** [comment]
Fixed in #52. Please try with version 1.9.1 which should hopefully fix it.
Thanks!
